### PR TITLE
Fixes multi-select widget for ipywidgets7

### LINKED ISSUE #179: Selection not displayed if multi=true
After a recent update the selection widget stopped being displayed when it has the keyword argument multi=true.
screen shot 2017-09-17 at 15 13 23

### PR DESCRIPTION
**Pull request by JobJob**
Seems to fix #179 - haven't tested it breaking other stuff though...

### CODE REVIEW

File: src/IJulia/handle_msg.jl [hunk 1]
```diff
@@ -21,6 +21,9 @@ function handle_msg{T}(w::Button{T}, msg)
     end
 end
 
+# keys2idx(x::OptionDict, ks) = findin(keys(s.options), ks)
+idxs2keys(x::Interact.OptionDict, indexes) = collect(keys(s.options))[indexes .+ 1]
```
Comment (korsbo) [inline src/IJulia/handle_msg.jl]: I think that the s.options is causing a bug here.

Comment (korsbo) [reply src/IJulia/handle_msg.jl]: Changing `s.options` to `x` makes it all better. I have already tested it.

Comment (JobJob) [reply src/IJulia/handle_msg.jl]: Nice one. I got (un)lucky, I was using your code to test it:
```
s = selection([:x, :y], multi=true, value=:y)
display(s)
signal(s)
```
so it was picking up the `s` from there.
